//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsCatalog.Languages.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ToolsCatalog.Languages.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  [
        ///   {
        ///      &quot;Lcid&quot;:54,
        ///      &quot;LanguageName&quot;:&quot;Afrikaans&quot;,
        ///      &quot;CountryName&quot;:null
        ///   },
        ///   {
        ///      &quot;Lcid&quot;:28,
        ///      &quot;LanguageName&quot;:&quot;Albanisch&quot;,
        ///      &quot;CountryName&quot;:null
        ///   },
        ///   {
        ///      &quot;Lcid&quot;:94,
        ///      &quot;LanguageName&quot;:&quot;Amharisch&quot;,
        ///      &quot;CountryName&quot;:null
        ///   },
        ///   {
        ///      &quot;Lcid&quot;:1,
        ///      &quot;LanguageName&quot;:&quot;Arabisch&quot;,
        ///      &quot;CountryName&quot;:null
        ///   },
        ///   {
        ///      &quot;Lcid&quot;:43,
        ///      &quot;LanguageName&quot;:&quot;Armenisch&quot;,
        ///      &quot;CountryName&quot;:null
        ///   },
        ///   {
        ///      &quot;Lcid&quot;:44,
        ///      &quot;LanguageName&quot;:&quot;Aserb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Languages_de_json {
            get {
                return ResourceManager.GetString("Languages_de_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  [
        ///   {
        ///      &quot;Lcid&quot;:54,
        ///      &quot;LanguageName&quot;:&quot;Afrikaans&quot;,
        ///      &quot;CountryName&quot;:null
        ///   },
        ///   {
        ///      &quot;Lcid&quot;:28,
        ///      &quot;LanguageName&quot;:&quot;Albanian&quot;,
        ///      &quot;CountryName&quot;:null
        ///   },
        ///   {
        ///      &quot;Lcid&quot;:132,
        ///      &quot;LanguageName&quot;:&quot;Alsatian&quot;,
        ///      &quot;CountryName&quot;:null
        ///   },
        ///   {
        ///      &quot;Lcid&quot;:94,
        ///      &quot;LanguageName&quot;:&quot;Amharic&quot;,
        ///      &quot;CountryName&quot;:null
        ///   },
        ///   {
        ///      &quot;Lcid&quot;:1,
        ///      &quot;LanguageName&quot;:&quot;Arabic&quot;,
        ///      &quot;CountryName&quot;:null
        ///   },
        ///   {
        ///      &quot;Lcid&quot;:43,
        ///      &quot;LanguageName&quot;:&quot;Armenian&quot;, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Languages_en_json {
            get {
                return ResourceManager.GetString("Languages_en_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  [
        ///   {
        ///      &quot;Lcid&quot;:54,
        ///      &quot;LanguageName&quot;:&quot;Afrikaans&quot;,
        ///      &quot;CountryName&quot;:null
        ///   },
        ///   {
        ///      &quot;Lcid&quot;:28,
        ///      &quot;LanguageName&quot;:&quot;Albanais&quot;,
        ///      &quot;CountryName&quot;:null
        ///   },
        ///   {
        ///      &quot;Lcid&quot;:7,
        ///      &quot;LanguageName&quot;:&quot;Allemand&quot;,
        ///      &quot;CountryName&quot;:null
        ///   },
        ///   {
        ///      &quot;Lcid&quot;:132,
        ///      &quot;LanguageName&quot;:&quot;Alsacien&quot;,
        ///      &quot;CountryName&quot;:null
        ///   },
        ///   {
        ///      &quot;Lcid&quot;:94,
        ///      &quot;LanguageName&quot;:&quot;Amharique&quot;,
        ///      &quot;CountryName&quot;:null
        ///   },
        ///   {
        ///      &quot;Lcid&quot;:9,
        ///      &quot;LanguageName&quot;:&quot;Anglais [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Languages_fr_json {
            get {
                return ResourceManager.GetString("Languages_fr_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  [
        ///   {
        ///      &quot;Lcid&quot;:54,
        ///      &quot;SystemLcid&quot;:54,
        ///      &quot;IsNeutral&quot;:true,
        ///      &quot;IsToolsCatalogSpecific&quot;:false,
        ///      &quot;IsUncorrected&quot;:false,
        ///      &quot;IsSimplified&quot;:false,
        ///      &quot;Name&quot;:&quot;af&quot;,
        ///      &quot;Children&quot;:[
        ///         {
        ///            &quot;Lcid&quot;:33846,
        ///            &quot;SystemLcid&quot;:1078,
        ///            &quot;IsNeutral&quot;:false,
        ///            &quot;IsToolsCatalogSpecific&quot;:true,
        ///            &quot;IsUncorrected&quot;:false,
        ///            &quot;IsSimplified&quot;:true,
        ///            &quot;Name&quot;:&quot;af-SF&quot;,
        ///            &quot;DefaultCodePage&quot;:1252,
        ///            &quot;Abbreviation&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Languages_json {
            get {
                return ResourceManager.GetString("Languages_json", resourceCulture);
            }
        }
    }
}
